select * from Users
select * from Gardens
select * from Plants
select * from GardenPlant
select * from Instructions

--select * from Plants
--join Instructions on Instructions.plant_id = plants.id

INSERT INTO Instructions
VALUES
  ('Chinese Lantern with vibrant blossoms.', 501),
  ('Striking Monkshood with deep-blue spikes.', 527),
  ('Fuzzy leaves, tubular colorful flowers.', 438),
  ('Tropical Elephant Ear, bold foliage.', 442),
  ('Healing succulent with spiky leaves.', 397),
  ('Elegant blooms, indoor flowering bulb.', 448),
  ('Delicate flowers, whimsical garden addition.', 475),
  ('Wildflower beauty, varied petal colors.', 459),
  ('Feathery plumes, shade garden favorite.', 467),
  ('Spring-blooming shrub, vibrant colors.', 414),
  ('Unique blossoms resemble balloons.', 502),
  ('Tall grass, versatile landscape addition.', 396),
  ('Fragrant herb for culinary use.', 418),
  ('Attracts bees, aromatic foliage.', 476),
  ('Colorful flowers, diverse leaf shapes.', 449),
  ('Bell-shaped blooms, cottage charm.', 528),
  ('Evergreen ground cover, bold leaves.', 477),
  ('Exotic tropical plant, striking appearance.', 441),
  ('Distinct heart-shaped flowers, shade-loving.', 466),
  ('Vibrant climber, paper-like bracts.', 411),
  ('Succulent, adapted to arid climates.', 390),
  ('Colorful foliage, shade-loving perennial.', 478),
  ('Elegant evergreen, waxy blooms.', 468),
  ('Bell-shaped flowers, garden classic.', 503),
  ('Fragrant blooms, versatile cut flower.', 401),
  ('Aromatic herb, attracts felines.', 431),
  ('Herbal tea, soothing properties.', 429),
  ('Iconic spring blooms, ornamental tree.', 402),
  ('Winter-flowering succulent, festive blooms.', 444),
  ('Fall favorite, diverse flower forms.', 413),
  ('Culinary herb, pungent leaves.', 427),
  ('Colorful foliage, shade-loving annual.', 479),
  ('Dainty daisy-like flowers, sunny delight.', 458),
  ('Culinary herb, aromatic seeds.', 423),
  ('Unique tubular blooms, heat-tolerant.', 529),
  ('Coneflower, medicinal and ornamental.', 453),
  ('Large, tropical foliage plant.', 398),
  ('Delicate ground cover, spring flowers.', 406),
  ('Indoor tree, air-purifying qualities.', 388),
  ('Large leaves, popular indoor tree.', 530),
  ('Graceful foliage, versatile garden plant.', 463),
  ('Colorful blooms, elegant maple-like leaves.', 457),
  ('Small blue flowers, charming groundcover.', 424),
  ('Early spring, vibrant yellow blossoms.', 504),
  ('Tall spikes, bell-shaped flowers.', 480),
  ('Hanging, tubular, vibrant blooms.', 481),
  ('Drought-tolerant, vibrant daisy-like flowers.', 531),
  ('Fragrant white blooms, evergreen shrub.', 505),
  ('Graceful, butterfly-like flowers, perennial.', 391),
  ('Graceful ornamental grass, shade-loving.', 452),
  ('Fragrant purple flowers, sweet scent.', 446),
  ('Winter-blooming, unique and elegant.', 532),
  ('Colorful foliage, versatile perennial.', 506),
  ('Large blooms, tropical appeal.', 456),
  ('Lush foliage, shade garden favorite.', 482),
  ('Wax plant, trailing vines, distinctive.', 462),
  ('Large blooms, color-changing petals.', 415),
  ('Evergreen ground cover, white flowers.', 483),
  ('Colorful, shade-loving annual flowers.', 507),
  ('Elegant sword-shaped leaves, vibrant blooms.', 533),
  ('Versatile ground cover, climbing.', 534),
  ('Ornamental tree, purple blooms.', 508),
  ('Unique, hooded flower structure.', 469),
  ('Succulent, resilient, indoor favorite.', 484),
  ('Fragrant, climbing vines, white flowers.', 410),
  ('Hen and chicks, succulent rosettes.', 464),
  ('Succulent, vibrant, long-lasting blooms.', 450),
  ('Native evergreen shrub, showy.', 399),
  ('Ground cover, yellow blooms.', 485),
  ('Evergreen shrub, colorful foliage.', 509),
  ('Tall spikes, purple feathery blooms.', 465),
  ('Elegant blooms, diverse varieties.', 403),
  ('Trailing or upright, vibrant flowers.', 510),
  ('Evergreen shrub, colorful foliage.', 486),
  ('Spikes of pea-like flowers.', 451),
  ('Vibrant spikes, cottage garden favorite.', 408),
  ('Iconic, fragrant, large blooms.', 535),
  ('Deciduous tree, vibrant foliage.', 445),
  ('Vibrant blooms, pest-repelling properties.', 511),
  ('Sensitive plant, fern-like leaves.', 536),
  ('Aromatic herb, culinary uses.', 404),
  ('Colorful, daisy-like blooms, diverse.', 421),
  ('Low-maintenance, trailing vines.', 487),
  ('Early spring blooms, vibrant colors.', 389),
  ('Elegant white blooms, air-purifying.', 454),
  ('Tubular flowers, perennial favorite.', 512),
  ('Large, fragrant blooms, perennial.', 537),
  ('Aromatic herb, culinary and medicinal.', 470),
  ('Climbing vine, heart-shaped leaves.', 513),
  ('Fragrant, carpet-like blooms, diverse.', 393),
  ('Evergreen tree, iconic cones.', 400),
  ('Papery blooms, vibrant colors.', 538),
  ('Low-maintenance, trailing vines.', 419),
  ('Early spring blooms, vibrant colors.', 488),
  ('Diverse species, early spring flowers.', 436),
  ('Graceful ornamental grass, unique.', 412),
  ('Cypress Vine, feathery foliage.', 471),
  ('Deciduous shrub, spring blooms.', 539),
  ('Rose-like blooms, vibrant colors.', 514),
  ('Evergreen shrub, showy flowers.', 460),
  ('Drought-tolerant, sunny blooms.', 489),
  ('Classic symbol, diverse varieties.', 394),
  ('Aromatic herb, needle-like leaves.', 392),
  ('Indoor tree, broad leaves.', 426),
  ('Black-Eyed Susan, golden blooms.', 490),
  ('Aromatic herb, gray-green leaves.', 515),
  ('Distinct species, fragrant blooms.', 428),
  ('Colorful, fragrant flowers.', 435),
  ('Gray-green foliage, aromatic blooms.', 491),
  ('Pincushion Flower, delicate blooms.', 405),
  ('Umbrella Plant, tropical foliage.', 430),
  ('Sansevieria, resilient indoor plant.', 447),
  ('Spiky blooms, vibrant colors.', 516),
  ('Chlorophytum, arching greenery.', 395),
  ('Ornamental shrub, cascading blooms.', 409),
  ('Water-storing plants, diverse shapes.', 440),
  ('Iconic blooms, sunny disposition.', 455),
  ('Spiky flower heads, architectural.', 540),
  ('Culinary herb, aromatic leaves.', 541),
  ('Striking blooms, orange hues.', 492),
  ('Wandering Jew, trailing foliage.', 517),
  ('Spring bulbs, iconic blooms.', 493),
  ('Evergreen tree, unique appearance.', 518),
  ('Schefflera, glossy green foliage.', 542),
  ('Ground cover, red berries.', 385),
  ('Clusters of small blooms, medicinal.', 425),
  ('Spreading blooms, vibrant colors.', 437);